spring:
  application:
    name: iplatform-moex
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false