package space.eliseev.iplatformmoex.entity;

public enum Board {
    TQIF("TQIF"), TQTF("TQTF"), TQBR("TQBR"),
    TQBS("TQBS"), TQNL("TQNL"), TQLV("TQLV"),
    TQLI("TQLI"), TQNE("TQNE"), TQDE("TQDE"),
    TQPI("TQPI"), TQTD("TQTD"), TQFD("TQFD"),
    TQPD("TQPD"), EQBR("EQBR"), EQBS("EQBS"),
    EQNL("EQNL"), EQLV("EQLV"), EQDE("EQDE"),
    EQLI("EQLI"), EQNE("EQNE"), SPEQ("SPEQ"),
    SMAL("SMAL"), TQDP("TQDP"), EQDP("EQDP"),
    EQTD("EQTD"), TQBE("TQBE"), TQTE("TQTE"),
    TQFE("TQFE"), TQPE("TQPE"), EQTU("EQTU"),
    EQCC("EQCC"), TQOB("TQOB"), TQOS("TQOS"),
    TQNO("TQNO"), TQOV("TQOV"), TQNB("TQNB"),
    TQUS("TQUS"), TQCB("TQCB"), TQRD("TQRD"),
    TQIR("TQIR"), TQOD("TQOD"), TQUD("TQUD"),
    TQIU("TQIU"), TQTC("TQTC"), EQOB("EQOB"),
    EQOS("EQOS"), EQNO("EQNO"), EQOV("EQOV"),
    EQDB("EQDB"), EQNB("EQNB"), EQUS("EQUS"),
    EQEO("EQEO"), SPOB("SPOB"), EQTC("EQTC"),
    EQEU("EQEU"), EQGO("EQGO"), EQYO("EQYO"),
    AUBB("AUBB"), AUCT("AUCT"), TQDB("TQDB"),
    TQOE("TQOE"), TQED("TQED"), TQIE("TQIE"),
    TQDU("TQDU"), TQOY("TQOY"), TQIY("TQIY"),
    PACT("PACT"), RPMO("RPMO"), RPEQ("RPEQ"),
    RPMA("RPMA"), RPEU("RPEU"), RPUA("RPUA"),
    RPUO("RPUO"), RPEO("RPEO"), RPEY("RPEY"),
    RPGO("RPGO"), RPCC("RPCC"), PTEU("PTEU"),
    PTIF("PTIF"), PTTC("PTTC"), PTTF("PTTF"),
    PTEQ("PTEQ"), PTES("PTES"), PTNL("PTNL"),
    PTLV("PTLV"), PTLI("PTLI"), PTNE("PTNE"),
    PTNO("PTNO"), PTUS("PTUS"), PTDE("PTDE"),
    PTPI("PTPI"), PSTD("PSTD"), PSFD("PSFD"),
    PSPD("PSPD"), PSIF("PSIF"), PSTC("PSTC"),
    PSTF("PSTF"), PSEQ("PSEQ"), PSES("PSES"),
    PSNL("PSNL"), PSLV("PSLV"), PSDE("PSDE"),
    PSLI("PSLI"), PSNE("PSNE"), PSOS("PSOS"),
    PSNO("PSNO"), PSOV("PSOV"), PSNB("PSNB"),
    PSUS("PSUS"), PSPI("PSPI"), PSGO("PSGO"),
    PSAU("PSAU"), PAUS("PAUS"), PAEU("PAEU"),
    PACY("PACY"), PAGB("PAGB"), PSBB("PSBB"),
    PSBE("PSBE"), OTCB("OTCB"), OTCU("OTCU"),
    OTCE("OTCE"), PTTD("PTTD"), PTFD("PTFD"),
    PTPD("PTPD"), PSBU("PSBU"), PTOE("PTOE"),
    PTED("PTED"), PTIE("PTIE"), PSSE("PSSE"),
    PSTE("PSTE"), PSFE("PSFE"), PSPE("PSPE"),
    PTSE("PTSE"), PTTE("PTTE"), PTFE("PTFE"),
    PTPE("PTPE"), PTOB("PTOB"), PTOS("PTOS"),
    PTOV("PTOV"), PTNB("PTNB"), PTDB("PTDB"),
    PTIR("PTIR"), PTOD("PTOD"), PTUD("PTUD"),
    PTIU("PTIU"), PSOB("PSOB"), PSDB("PSDB"),
    PSIR("PSIR"), PSEU("PSEU"), PSUD("PSUD"),
    PSIU("PSIU"), PSEO("PSEO"), PSED("PSED"),
    PSIE("PSIE"), PSYO("PSYO"), PSIY("PSIY"),
    PTIY("PTIY"), PSCC("PSCC"), SNDX("SNDX"),
    RTSI("RTSI"), INAV("INAV"), MMIX("MMIX"),
    AGRO("AGRO"), SDII("SDII"), STMR("STMR"),
    SDMR("SDMR"), STAD("STAD"), SDAD("SDAD"),
    STRP("STRP"), SDRP("SDRP"), CLMR("CLMR"),
    CLAD("CLAD"), EQRD("EQRD"), EQRE("EQRE"),
    EQWP("EQWP"), EQWD("EQWD"), EQWE("EQWE"),
    EQRP("EQRP"), EQMP("EQMP"), EQMD("EQMD"),
    EQME("EQME"), EQTP("EQTP"), ETQD("ETQD"),
    EQTE("EQTE"), LIQR("LIQR"), EQRY("EQRY"),
    PSRY("PSRY"), PSRP("PSRP"), PSRD("PSRD"),
    PSRE("PSRE"), FKRP("FKRP"), FKOW("FKOW"),
    FKSW("FKSW"), FKFW("FKFW"), FKOM("FKOM"),
    FKSM("FKSM"), FKTM("FKTM"), FKUM("FKUM"),
    FKOY("FKOY"), FRRP("FRRP"), FROW("FROW"),
    FRSW("FRSW"), FRFW("FRFW"), FROM("FROM"),
    FRTM("FRTM"), TQQI("TQQI"), EQQI("EQQI"),
    PSQI("PSQI"), PTQI("PTQI"), RPQI("RPQI"),
    RPUQ("RPUQ"), TQQD("TQQD"), SOTC("SOTC"),
    MXBD("MXBD"), TDEP("TDEP"), NDEP("NDEP"),
    NDPU("NDPU"), NDPE("NDPE"), TDPU("TDPU"),
    TDPE("TDPE"), ADEP("ADEP"), LIQB("LIQB"),
    CIQB("CIQB"), GCRP("GCRP"), GCOW("GCOW"),
    GCSW("GCSW"), GCOM("GCOM"), GCSM("GCSM"),
    GCTM("GCTM"), GCUM("GCUM"), GCOY("GCOY"),
    PSGC("PSGC"), GURP("GURP"), GUOW("GUOW"),
    GUSW("GUSW"), GUOM("GUOM"), GUSM("GUSM"),
    GUTM("GUTM"), GUUM("GUUM"), GUOY("GUOY"),
    PUGC("PUGC"), GERP("GERP"), GEOW("GEOW"),
    GESW("GESW"), GEOM("GEOM"), GESM("GESM"),
    GETM("GETM"), GEUM("GEUM"), GEOY("GEOY"),
    PEGC("PEGC"), GCNM("GCNM"), GUNM("GUNM"),
    GENM("GENM"), FQBR("FQBR"), FQDE("FQDE"),
    TQBD("TQBD"), TQDD("TQDD"), PTSD("PTSD"),
    PTDD("PTDD"), PSSD("PSSD"), PSDD("PSDD"),
    FTEQ("FTEQ"), FTDE("FTDE"), FSEQ("FSEQ"),
    FSDE("FSDE"), CRER("CRER"), CREU("CREU"),
    CREE("CREE"), CTEQ("CTEQ"), CTSD("CTSD"),
    CTSE("CTSE"), CTOB("CTOB"), CTIY("CTIY"),
    CTOD("CTOD"), CTOE("CTOE"), CPMO("CPMO"),
    CPEU("CPEU"), CPEO("CPEO"), CPEY("CPEY"),
    CIQR("CIQR"), MAIN("MAIN"), RPDD("RPDD"),
    NEGD("NEGD"), GNDX("GNDX"), CETS("CETS"),
    SDBP("SDBP"), CURR("CURR"), CNGD("CNGD"),
    LICU("LICU"), FIXS("FIXS"), FIXN("FIXN"),
    WAPS("WAPS"), WAPN("WAPN"), AUCB("AUCB"),
    SPEC("SPEC"), FUTS("FUTS"), FUTN("FUTN"),
    FIXI("FIXI"), OTCT("OTCT"), OTCF("OTCF"),
    FOB("FOB"), RFUD("RFUD"), ROPD("ROPD"),
    FIQS("FIQS"), OIQS("OIQS"), FOCM("FOCM"),
    GSEL("GSEL"), OBBO("OBBO"), SUGR("SUGR"),
    ABGR("ABGR"), OCTR("OCTR"), OCTU("OCTU"),
    OCBR("OCBR"), OCBU("OCBU");

    private String boardid;
    Board(String boardid) {
        this.boardid = boardid;
    }

    public String getBoardid() {
        return boardid;
    }
}
